---
title: "Project 1"
author: "Brian Sugg"
date: "6/12/2020"
output:
  rmarkdown::github_document:
    toc: true
    toc_depth: 3
  html_document:
    toc: true
    toc_depth: 3
---

# Introduction to JSON Data  

## Background  

Describe JSON data. What is it, where does it get used, and why is it a good way to store data? This should be detailed enough that someone that hasn’t seen JSON data would have a good idea what they are dealing with. Link to references where applicable.  

## Reading JSON DATA into R  

Discuss the possible packages/functions that are available for reading JSON data into R.  

### Package 1  

Details on available package 1 (to be named).  

### Package 2  

Details on available package 2 (to be named).  

### Package 3  

Details on available package 1 (to be named).  

## Package for this Vignette  

Name which package will be used in the upcoming API call to NHL records, and why.  

# NHL Franchise API  

## Background  

Provide info on the NHL, available tables from records.nhl.com, which tables will be explored using the selected function.  

## Establishing API Connection  

Code chunk for the API and returning parse data from the selected tables.  

## Exploratory Data Analysis  

### The Data  

Check for any needed formatting, create a new variable as required.  

### Numeric Summaries  

Provide contingecy tables and numeric summaries as required.  

### Visuals  

Create some plots (bar, box, scatter) with discussion of observations for each.  
